-- Run this in Vercel Storage -> your database -> Query, AFTER creating
-- the meetings table. 8 records with varied meeting_type and speaker
-- names so search is verifiable (try /meetings?query=smith once seeded).

INSERT INTO meetings
  (date, meeting_type, presiding, conducting, announcements,
   opening_hymn, opening_prayer, ward_business, stake_business,
   sacrament_hymn, speakers, closing_hymn, closing_prayer)
VALUES
('2026-08-02', 'regular', 'Bishop Ramirez', 'Elder Torres, First Counselor',
  ARRAY['Ward temple day this Saturday', 'Youth activity Friday at 6pm'],
  '{"number":19,"title":"We Thank Thee, O God, for a Prophet"}',
  'Sister Fernandez',
  '[{"description":"Sustaining of new Primary teacher, Sister Gomez"}]',
  false,
  '{"number":169,"title":"As Now We Take the Sacrament"}',
  '[{"name":"Brother Diaz","topic":"Faith in Christ","type":"speaker"},{"name":"Youth Choir","topic":"Musical Number","type":"musical-number"},{"name":"Sister Alvarez","topic":"Enduring to the End","type":"speaker"}]',
  '{"number":219,"title":"Because I Have Been Given Much"}',
  'Brother Nunez'),

('2026-08-09', 'testimony', 'Bishop Ramirez', 'Bishop Ramirez',
  ARRAY['Fast and testimony meeting today'],
  '{"number":30,"title":"Come, Come, Ye Saints"}',
  'Brother Castillo',
  '[]',
  false,
  '{"number":173,"title":"In Humility, Our Savior"}',
  '[]',
  '{"number":133,"title":"How Firm a Foundation"}',
  'Sister Marte'),

('2026-08-16', 'regular', 'Bishop Ramirez', 'Elder Pena, Second Counselor',
  ARRAY['Missionary farewell for Elder Cruz next week'],
  '{"number":89,"title":"Our Saviors Love"}',
  'Sister Ortiz',
  '[{"description":"Release of Brother Vargas as Elders Quorum secretary"}]',
  false,
  '{"number":174,"title":"Twas on That Dark, That Doleful Night"}',
  '[{"name":"Elder Cruz","topic":"Missionary farewell","type":"speaker"}]',
  '{"number":66,"title":"Rejoice, the Lord Is King!"}',
  'Brother Reyes'),

('2026-08-23', 'stake', 'Stake President Medina', 'Stake President Medina',
  ARRAY['Combined stake conference broadcast'],
  '{"number":1,"title":"The Morning Breaks"}',
  'Sister Paulino',
  '[]',
  true,
  '{"number":193,"title":"I Stand All Amazed"}',
  '[{"name":"Stake President Medina","topic":"Stake conference address","type":"speaker"}]',
  '{"number":249,"title":"Called to Serve"}',
  'Brother Guzman'),

('2026-08-30', 'regular', 'Bishop Ramirez', 'Elder Torres, First Counselor',
  ARRAY['Primary program next Sunday'],
  '{"number":92,"title":"Now Let Us Rejoice"}',
  'Brother Feliz',
  '[{"description":"Sustaining of new Sunday School president, Brother Mejia"}]',
  false,
  '{"number":181,"title":"While of These Emblems We Partake"}',
  '[{"name":"Sister Rosario","topic":"The Atonement of Jesus Christ","type":"speaker"},{"name":"Ward Choir","topic":"Musical Number","type":"musical-number"}]',
  '{"number":246,"title":"Love One Another"}',
  'Sister Lantigua'),

('2026-09-06', 'general', 'Bishop Ramirez', 'Bishop Ramirez',
  ARRAY['General Conference weekend'],
  '{"number":1,"title":"The Morning Breaks"}',
  'N/A',
  '[]',
  false,
  '{"number":1,"title":"N/A"}',
  '[]',
  '{"number":1,"title":"N/A"}',
  'N/A'),

('2026-09-13', 'testimony', 'Bishop Ramirez', 'Elder Pena, Second Counselor',
  ARRAY['Fast and testimony meeting'],
  '{"number":66,"title":"Rejoice, the Lord Is King!"}',
  'Sister Smith',
  '[]',
  false,
  '{"number":174,"title":"Behold the Great Redeemer Die"}',
  '[]',
  '{"number":19,"title":"We Thank Thee, O God, for a Prophet"}',
  'Brother Johnson'),

('2026-09-20', 'regular', 'Bishop Ramirez', 'Elder Torres, First Counselor',
  ARRAY['Ward campout this Saturday'],
  '{"number":30,"title":"Come, Come, Ye Saints"}',
  'Brother Martinez',
  '[{"description":"Sustaining of new Relief Society president, Sister Smith"}]',
  false,
  '{"number":169,"title":"As Now We Take the Sacrament"}',
  '[{"name":"Brother Smith","topic":"Faith and Family","type":"speaker"},{"name":"Sister Johnson","topic":"Musical Number","type":"musical-number"}]',
  '{"number":219,"title":"Because I Have Been Given Much"}',
  'Sister Alvarez');
